import React, { createContext, useContext, useState, useEffect } from 'react';

const LangContext = createContext();

const translations = {
  vi: {
    title: "📚 Kho Truyện Tổng Hợp",
    subtitle: "Gộp từ 7 nguồn: Ixdzs · Biquge · 41nr · Quanben · Faloo · Fanqie · Hjwzw",
    uniqueBooks: "Đầu truyện unique",
    dupSources: "Trùng ≥2 nguồn",
    sources: "Nguồn dữ liệu",
    tabDiscover: " Khám Phá",
    tabBookshelf: " Tủ Sách",
    tabHistory: " Lịch Sử",
    tabDeveloper: " API Developer",
    tabEmbed: " Nhúng Truyện",
    tabSettings: " Cài Đặt",
    searchPlaceholder: "Tìm tên truyện, tác giả, mô tả...",
    searchFieldAll: "🔎 Tất cả",
    searchFieldTitle: "📖 Tên truyện",
    searchFieldAuthor: "✍ Tác giả",
    searchFieldHanviet: "🏮 Hán Việt",
    searchFieldVietphrase: "📝 Việt dịch",
    searchFieldChinese: "🀄 Gốc Trung",
    searchFieldDesc: "📋 Mô tả",
    allCategories: "— Tất cả thể loại —",
    allSources: "— Tất cả nguồn —",
    allDup: "— Tất cả —",
    dupMulti: "Trùng nhiều nguồn (≥2)",
    dupSingle: "Chỉ 1 nguồn",
    allChapters: "— Số chương —",
    ch100: "≥ 100 chương",
    ch500: "≥ 500 chương",
    ch1000: "≥ 1000 chương",
    ch2000: "≥ 2000 chương",
    sortBy: {
      site_count: "Nhiều nguồn nhất",
      chapters_max: "Nhiều chương nhất",
      word_count_max: "Nhiều từ nhất",
      title_asc: "Tên A→Z",
      title_desc: "Tên Z→A",
      default: "Mặc định"
    },
    clearFilter: "✕ Xóa lọc",
    login: "Đăng Nhập",
    logout: "Đăng xuất",
    register: "Đăng Ký",
    loading: "⏳ Đang tải dữ liệu...",
    empty: "🔎 Không tìm thấy truyện nào",
    loginToViewBookshelf: "🔒 Vui lòng đăng nhập để xem tủ sách.",
    loginToViewHistory: "🔒 Vui lòng đăng nhập để xem lịch sử đọc.",
    emptyHistory: "⏳ Lịch sử trống",
    chapters: "Chương",
    words: "Từ",
    compareBtn: "So sánh 3 bản dịch",
    addBookshelf: "Thêm vào tủ",
    inBookshelf: "Đã lưu vào tủ",
    readExternal: "Đọc truyện ngoài ↗",
    removeExternal: "Xóa khỏi tủ",
    readBtn: "Đọc",
    lastView: "Lần cuối xem",
    clearHistoryBtn: "Xóa toàn bộ",
    results: "kết quả — trang",
    booksInShelf: "truyện trong tủ sách",
    readHistoryCount: "Lịch sử đọc",
    authRequired: "Vui lòng điền đầy đủ thông tin.",
    connError: "Lỗi kết nối server",
    regSuccess: "Đăng ký thành công! Hãy đăng nhập.",
    removeFavTitle: "⚠️ Xóa khỏi tủ sách",
    removeFavConfirm: "Bạn có chắc chắn muốn xóa truyện này khỏi tủ sách?",
    removeFavSuccess: "Đã xóa khỏi tủ sách",
    addFavSuccess: "Đã thêm vào tủ sách thành công!",
    clearHistConfirm: "Bạn có chắc chắn muốn xóa TOÀN BỘ lịch sử đọc truyện? Hành động này không thể hoàn tác.",
    clearHistSuccess: "Đã xóa toàn bộ lịch sử",
    comparingText: "⏳ Đang so sánh...",
    compFast: "⚡ Dịch Nhanh (Fast)",
    compAdvanced: "✨ Dịch Chất Lượng (Advanced)",
    compVietphrase: "📚 Dịch Vietphrase (Vietphrase)",
    compHanviet: "🏮 Hán Việt (Hanviet)",
    compError: "❌ Lỗi tải bản dịch",
    auth: {
      loginTitle: "Đăng Nhập",
      registerTitle: "Đăng Ký",
      verifyRegTitle: "Xác Minh Email",
      forgotTitle: "Quên Mật Khẩu",
      resetTitle: "Khôi Phục Mật Khẩu",
      usernamePlaceholder: "Tên đăng nhập hoặc Email",
      emailPlaceholder: "Email (Nhận OTP)",
      otpPlaceholder: "Nhập mã OTP từ Email",
      passwordPlaceholder: "Mật khẩu",
      newPasswordPlaceholder: "Mật khẩu mới",
      submitLogin: "Đăng Nhập",
      submitRegister: "Đăng Ký",
      submitForgot: "Gửi mã OTP",
      submitVerifyReg: "Xác Minh Tài Khoản",
      submitReset: "Đổi mật khẩu",
      resendOtpBtn: "Chưa nhận được mã? Gửi lại mã OTP",
      processing: "Đang xử lý...",
      noAccount: "Chưa có tài khoản?",
      registerNow: "Đăng ký ngay",
      forgotPassLink: "Quên mật khẩu?",
      haveAccount: "Đã có tài khoản?",
      backToLogin: "Quay lại Đăng nhập",
      verifySuccess: "Xác minh thành công! Vui lòng đăng nhập.",
      forgotOtpSent: "Mã OTP đã được gửi đến email của bạn.",
      resetSuccess: "Khôi phục mật khẩu thành công.",
      googleLoginError: "Lỗi đăng nhập Google",
      resendOtpSuccess: "Mã xác minh mới đã được gửi.",
      resendOtpError: "Lỗi gửi lại mã xác minh.",
      otpRequired: "Vui lòng nhập đầy đủ email và mã OTP xác minh.",
      fillAll: "Vui lòng điền đầy đủ thông tin."
    },
    settings: {
      title: "⚙️ Cài đặt Tài khoản",
      subtitle: "Quản lý mật khẩu, bảo mật và thông tin tài khoản của bạn.",
      reqLogin: "Yêu cầu đăng nhập",
      reqLoginDesc: "Vui lòng đăng nhập để truy cập trang Cài đặt tài khoản.",
      mustChangePassTitle: "Yêu cầu đặt mật khẩu mới",
      mustChangePassDesc: "Đây là lần đầu tiên bạn đăng nhập bằng Google. Vui lòng thiết lập mật khẩu riêng cho tài khoản để có thể đăng nhập trực tiếp bằng Email sau này.",
      freeMember: "Thành viên miễn phí",
      vipMember: "Thành viên VIP",
      emailLabel: "Địa chỉ Email",
      notSet: "Chưa thiết lập",
      vipExpiry: "Hạn VIP",
      changePassTitle: "Đổi Mật Khẩu",
      currentPassLabel: "Mật khẩu hiện tại",
      currentPassPlaceholder: "Nhập mật khẩu hiện tại",
      newPassLabel: "Mật khẩu mới",
      newPassPlaceholder: "Tối thiểu 4 ký tự",
      confirmPassLabel: "Xác nhận mật khẩu mới",
      confirmPassPlaceholder: "Xác nhận lại mật khẩu mới",
      updateBtn: "Cập nhật Mật khẩu",
      updating: "Đang cập nhật...",
      passMinLen: "Mật khẩu mới phải từ 4 ký tự trở lên.",
      passMismatch: "Mật khẩu mới và xác nhận mật khẩu không trùng khớp.",
      passChangeSuccess: "Đổi mật khẩu thành công!",
      passChangeError: "Lỗi thay đổi mật khẩu."
    },
    developer: {
      title: "🛠️ API Developer Console",
      subtitle: "Tạo và quản lý API Key của bạn để sử dụng dịch vụ dịch thuật và TTS qua API.",
      balance: "Số dư tài khoản API",
      vipServerRate: "Ưu đãi VIP: Tài khoản VIP được miễn phí các lượt gọi dịch thuật và TTS.",
      rateLimitWarning: "Lưu ý: Không lạm dụng rate limit của API.",
      apiKeyListTitle: "Danh sách API Key",
      createBtn: "Tạo API Key mới",
      keyNameLabel: "Tên API Key",
      keyNamePlaceholder: "Nhập tên gợi nhớ (ví dụ: Chrome Extension, App dịch...)",
      keyNameRequired: "Vui lòng nhập tên API Key.",
      creating: "Đang tạo...",
      copied: "Đã sao chép!",
      copyBtn: "Sao chép",
      revokedStatus: "Đã thu hồi",
      activeStatus: "Đang hoạt động",
      createdLabel: "Ngày tạo",
      lastUsedLabel: "Dùng cuối",
      neverUsed: "Chưa sử dụng",
      revokeBtn: "Thu hồi",
      revokeConfirm: "Bạn có chắc chắn muốn thu hồi API Key này? Tất cả các ứng dụng đang sử dụng key này sẽ bị ngắt kết nối.",
      revokeSuccess: "Thu hồi API Key thành công!",
      revokeError: "Lỗi thu hồi API Key.",
      createSuccess: "Tạo API Key thành công! Hãy sao chép key dưới đây vì nó sẽ không được hiển thị lại:",
      createError: "Lỗi tạo API Key.",
      apiDocsTitle: "Tài liệu API tích hợp",
      apiDocsDesc: "Bạn có thể sử dụng các endpoint dưới đây cho ứng dụng hoặc Extension của mình. Yêu cầu truyền Header `X-VIP-Key: <your_api_key>` hoặc Header `Authorization: Bearer <your_api_key>`.",
      transEndpoint: "1. API dịch thuật (Vietphrase / Smooth)",
      transPayloadDesc: "Payload gửi đi (POST):",
      ttsEndpoint: "2. API Text-to-Speech (TTS)",
      ttsPayloadDesc: "Payload gửi đi (POST):",
      voicesList: "Danh sách giọng nói hỗ trợ (gồm the_gioi_hoan_my, pha_bong_cau, ...)",
      apiUsageHistoryTitle: "Lịch sử cuộc gọi API",
      colKey: "API Key",
      colModel: "Model / Chức năng",
      colChars: "Độ dài / Số từ",
      colCost: "Chi phí",
      colStatus: "Trạng thái",
      colTime: "Thời gian",
      freeCost: "Miễn phí (VIP)",
      emptyUsage: "Chưa có cuộc gọi API nào được ghi lại."
    },
    reader: {
      nextChapter: "Chương Sau ❯",
      prevChapter: "❮ Chương Trước",
      toc: "Mục Lục",
      settings: "Cài Đặt",
      ttsPlayer: "Trình Đọc Thành Tiếng",
      playBtn: "Phát",
      pauseBtn: "Tạm dừng",
      stopBtn: "Dừng",
      speed: "Tốc độ",
      voice: "Giọng đọc",
      modeFast: "Bản dịch Nhanh",
      modeAdvanced: "Bản dịch VIP",
      modeHanviet: "Bản dịch Hán Việt",
      loadingChapter: "⏳ Đang tải nội dung chương...",
      errorLoadingChapter: "❌ Lỗi tải nội dung chương.",
      ttsLoading: "⏳ Đang tạo âm thanh...",
      ttsError: "❌ Lỗi phát âm thanh. Vui lòng thử lại sau.",
      epubSuccess: "Tải file EPUB thành công!"
    }
  },
  en: {
    title: "📚 Merged Novels Library",
    subtitle: "Merged from 7 sources: Ixdzs · Biquge · 41nr · Quanben · Faloo · Fanqie · Hjwzw",
    uniqueBooks: "Unique Novels",
    dupSources: "Duplicate ≥2 Sources",
    sources: "Data Sources",
    tabDiscover: " Discover",
    tabBookshelf: " Bookshelf",
    tabHistory: " History",
    tabDeveloper: " API Developer",
    tabEmbed: " Embed",
    tabSettings: " Settings",
    searchPlaceholder: "Search title, author, description...",
    searchFieldAll: "🔎 All Fields",
    searchFieldTitle: "📖 Title",
    searchFieldAuthor: "✍ Author",
    searchFieldHanviet: "🏮 Sino-Viet",
    searchFieldVietphrase: "📝 Translation",
    searchFieldChinese: "🀄 Chinese Original",
    searchFieldDesc: "📋 Description",
    allCategories: "— All Categories —",
    allSources: "— All Sources —",
    allDup: "— All Matches —",
    dupMulti: "Multi-Source (≥2)",
    dupSingle: "Single Source Only",
    allChapters: "— Chapters —",
    ch100: "≥ 100 ch",
    ch500: "≥ 500 ch",
    ch1000: "≥ 1000 ch",
    ch2000: "≥ 2000 ch",
    sortBy: {
      site_count: "Most Sources",
      chapters_max: "Most Chapters",
      word_count_max: "Most Words",
      title_asc: "Title A→Z",
      title_desc: "Title Z→A",
      default: "Default ID"
    },
    clearFilter: "✕ Clear Filters",
    login: "Log In",
    logout: "Log Out",
    register: "Register",
    loading: "⏳ Loading data...",
    empty: "🔎 No novels found",
    loginToViewBookshelf: "🔒 Please log in to view your bookshelf.",
    loginToViewHistory: "🔒 Please log in to view your history.",
    emptyHistory: "⏳ History is empty",
    chapters: "Ch",
    words: "Words",
    compareBtn: "Compare 3 Translations",
    addBookshelf: "Save to Shelf",
    inBookshelf: "Saved in Shelf",
    readExternal: "Read External ↗",
    removeExternal: "Remove",
    readBtn: "Read",
    lastView: "Last viewed",
    clearHistoryBtn: "Clear All",
    results: "results — page",
    booksInShelf: "novels in bookshelf",
    readHistoryCount: "Reading History",
    authRequired: "Please fill in all fields.",
    connError: "Server connection error",
    regSuccess: "Registration successful! Please log in.",
    removeFavTitle: "⚠️ Remove from bookshelf",
    removeFavConfirm: "Are you sure you want to remove this novel from your bookshelf?",
    removeFavSuccess: "Removed from bookshelf",
    addFavSuccess: "Successfully added to bookshelf!",
    clearHistConfirm: "Are you sure you want to clear ALL reading history? This action cannot be undone.",
    clearHistSuccess: "Successfully cleared reading history",
    comparingText: "⏳ Comparing...",
    compFast: "⚡ Fast Translation",
    compAdvanced: "✨ Advanced Translation",
    compVietphrase: "📚 Vietphrase Translation",
    compHanviet: "🏮 Sino-Viet (Hanviet)",
    compError: "❌ Error loading translations",
    auth: {
      loginTitle: "Log In",
      registerTitle: "Register",
      verifyRegTitle: "Verify Email",
      forgotTitle: "Forgot Password",
      resetTitle: "Reset Password",
      usernamePlaceholder: "Username or Email",
      emailPlaceholder: "Email (To get OTP)",
      otpPlaceholder: "Enter OTP code from Email",
      passwordPlaceholder: "Password",
      newPasswordPlaceholder: "New Password",
      submitLogin: "Log In",
      submitRegister: "Register",
      submitForgot: "Send OTP",
      submitVerifyReg: "Verify Account",
      submitReset: "Reset Password",
      resendOtpBtn: "Didn't receive code? Resend OTP",
      processing: "Processing...",
      noAccount: "Don't have an account?",
      registerNow: "Register now",
      forgotPassLink: "Forgot password?",
      haveAccount: "Already have an account?",
      backToLogin: "Back to Login",
      verifySuccess: "Verification successful! Please log in.",
      forgotOtpSent: "OTP has been sent to your email.",
      resetSuccess: "Password reset successful.",
      googleLoginError: "Google login error",
      resendOtpSuccess: "New verification code has been sent.",
      resendOtpError: "Error resending verification code.",
      otpRequired: "Please enter your email and verification OTP.",
      fillAll: "Please fill in all required fields."
    },
    settings: {
      title: "⚙️ Account Settings",
      subtitle: "Manage your passwords, security and account details.",
      reqLogin: "Login Required",
      reqLoginDesc: "Please log in to access the Settings page.",
      mustChangePassTitle: "New Password Required",
      mustChangePassDesc: "This is your first time logging in with Google. Please set a unique password to log in directly via email later.",
      freeMember: "Free Member",
      vipMember: "VIP Member",
      emailLabel: "Email Address",
      notSet: "Not set",
      vipExpiry: "VIP Expiry",
      changePassTitle: "Change Password",
      currentPassLabel: "Current Password",
      currentPassPlaceholder: "Enter current password",
      newPassLabel: "New Password",
      newPassPlaceholder: "Minimum 4 characters",
      confirmPassLabel: "Confirm New Password",
      confirmPassPlaceholder: "Re-enter new password",
      updateBtn: "Update Password",
      updating: "Updating...",
      passMinLen: "New password must be at least 4 characters.",
      passMismatch: "Passwords do not match.",
      passChangeSuccess: "Password changed successfully!",
      passChangeError: "Error changing password."
    },
    developer: {
      title: "🛠️ API Developer Console",
      subtitle: "Create and manage your API keys to consume translation and TTS services via API.",
      balance: "API Account Balance",
      vipServerRate: "VIP Benefit: VIP accounts call translation & TTS APIs for free.",
      rateLimitWarning: "Note: Please do not abuse API rate limits.",
      apiKeyListTitle: "API Key List",
      createBtn: "Create New API Key",
      keyNameLabel: "API Key Name",
      keyNamePlaceholder: "Enter a nickname (e.g. Chrome Extension, Translation App...)",
      keyNameRequired: "Please enter API Key name.",
      creating: "Creating...",
      copied: "Copied!",
      copyBtn: "Copy",
      revokedStatus: "Revoked",
      activeStatus: "Active",
      createdLabel: "Created At",
      lastUsedLabel: "Last Used",
      neverUsed: "Never",
      revokeBtn: "Revoke",
      revokeConfirm: "Are you sure you want to revoke this API key? All applications using this key will be disconnected.",
      revokeSuccess: "API Key revoked successfully!",
      revokeError: "Error revoking API Key.",
      createSuccess: "API Key created successfully! Copy it below, it will not be shown again:",
      createError: "Error creating API Key.",
      apiDocsTitle: "API Integration Documentation",
      apiDocsDesc: "Use these endpoints in your extension or app. Pass `X-VIP-Key: <your_api_key>` or `Authorization: Bearer <your_api_key>` headers.",
      transEndpoint: "1. Translation API (Vietphrase / Smooth)",
      transPayloadDesc: "Payload (POST):",
      ttsEndpoint: "2. Text-to-Speech (TTS) API",
      ttsPayloadDesc: "Payload (POST):",
      voicesList: "Supported voices list (includes the_gioi_hoan_my, pha_bong_cau, ...)",
      apiUsageHistoryTitle: "API Usage Logs",
      colKey: "API Key",
      colModel: "Model / Feature",
      colChars: "Chars / Words",
      colCost: "Cost",
      colStatus: "Status",
      colTime: "Time",
      freeCost: "Free (VIP)",
      emptyUsage: "No API calls recorded yet."
    },
    reader: {
      nextChapter: "Next Chapter ❯",
      prevChapter: "❮ Prev Chapter",
      toc: "TOC",
      settings: "Settings",
      ttsPlayer: "Text-to-Speech Player",
      playBtn: "Play",
      pauseBtn: "Pause",
      stopBtn: "Stop",
      speed: "Speed",
      voice: "Voice",
      modeFast: "Fast Translation",
      modeAdvanced: "VIP Translation",
      modeHanviet: "Sino-Viet Translation",
      loadingChapter: "⏳ Loading chapter content...",
      errorLoadingChapter: "❌ Error loading chapter.",
      ttsLoading: "⏳ Generating audio...",
      ttsError: "❌ Error generating audio. Please try again.",
      epubSuccess: "EPUB file downloaded successfully!"
    }
  },
  zh: {
    title: "📚 聚合小说书库",
    subtitle: "聚合自7个源站: 爱下电子书 · 笔趣阁 · 41nr · 全本书首 · 飞卢 · 番茄 · 红袖添香",
    uniqueBooks: "独家小说数",
    dupSources: "重合 ≥2 来源",
    sources: "数据源数量",
    tabDiscover: " 发现小说",
    tabBookshelf: " 我的书架",
    tabHistory: " 阅读历史",
    tabDeveloper: " 开发者中心",
    tabEmbed: " 嵌入阅读",
    tabSettings: " 账户设置",
    searchPlaceholder: "搜索书名、作者、简介...",
    searchFieldAll: "🔎 全文搜索",
    searchFieldTitle: "📖 按书名",
    searchFieldAuthor: "✍ 按作者",
    searchFieldHanviet: "🏮 汉越音译",
    searchFieldVietphrase: "📝 越文翻译",
    searchFieldChinese: "🀄 中文原名",
    searchFieldDesc: "📋 按简介",
    allCategories: "— 全部题材 —",
    allSources: "— 全部来源 —",
    allDup: "— 重合筛选 —",
    dupMulti: "多站重合 (≥2)",
    dupSingle: "仅单一来源",
    allChapters: "— 章节字数 —",
    ch100: "≥ 100 章",
    ch500: "≥ 500 章",
    ch1000: "≥ 1000 章",
    ch2000: "≥ 2000 章",
    sortBy: {
      site_count: "来源最多",
      chapters_max: "章节最多",
      word_count_max: "字数最多",
      title_asc: "书名 A→Z",
      title_desc: "书名 Z→A",
      default: "默认排序"
    },
    clearFilter: "✕ 清除筛选",
    login: "登录",
    logout: "退出",
    register: "注册",
    loading: "⏳ 正在加载数据...",
    empty: "🔎 未找到匹配小说",
    loginToViewBookshelf: "🔒 请先登录以查看您的书架。",
    loginToViewHistory: "🔒 请先登录以查看您的历史记录。",
    emptyHistory: "⏳ 历史记录为空",
    chapters: "章",
    words: "字",
    compareBtn: "对比三种翻译",
    addBookshelf: "收藏至书架",
    inBookshelf: "已收藏",
    readExternal: "打开原站 ↗",
    removeExternal: "取消收藏",
    readBtn: "阅读",
    lastView: "最后阅读",
    clearHistoryBtn: "清空历史",
    results: "个结果 — 第",
    booksInShelf: "本收藏小说",
    readHistoryCount: "阅读历史记录",
    authRequired: "请填写所有字段。",
    connError: "服务器连接错误",
    regSuccess: "注册成功！请登录。",
    removeFavTitle: "⚠️ 移出书架",
    removeFavConfirm: "您确定要将这部小说从书架中移出吗？",
    removeFavSuccess: "已从书架中移出",
    addFavSuccess: "成功加入书架！",
    clearHistConfirm: "您确定要清空所有阅读历史记录吗？此操作无法撤销。",
    clearHistSuccess: "已成功清空阅读历史记录",
    comparingText: "⏳ 正在对比...",
    compFast: "⚡ 快速翻译",
    compAdvanced: "✨ 高级优质翻译",
    compVietphrase: "📚 越文词库翻译",
    compHanviet: "🏮 汉越音译",
    compError: "❌ 加载翻译失败",
    auth: {
      loginTitle: "登录",
      registerTitle: "注册",
      verifyRegTitle: "验证邮箱",
      forgotTitle: "忘记密码",
      resetTitle: "重置密码",
      usernamePlaceholder: "用户名或邮箱",
      emailPlaceholder: "电子邮箱 (用于接收验证码)",
      otpPlaceholder: "输入邮箱中的验证码",
      passwordPlaceholder: "密码",
      newPasswordPlaceholder: "新密码",
      submitLogin: "登录",
      submitRegister: "注册",
      submitForgot: "发送验证码",
      submitVerifyReg: "验证并激活账号",
      submitReset: "修改密码",
      resendOtpBtn: "未收到验证码？重新发送",
      processing: "处理中...",
      noAccount: "还没有账号？",
      registerNow: "立即注册",
      forgotPassLink: "忘记密码？",
      haveAccount: "已有账号？",
      backToLogin: "返回登录",
      verifySuccess: "验证成功！请登录。",
      forgotOtpSent: "验证码已发送至您的邮箱。",
      resetSuccess: "密码重置成功。",
      googleLoginError: "谷歌登录出错",
      resendOtpSuccess: "新验证码已发送。",
      resendOtpError: "发送验证码出错。",
      otpRequired: "请完整输入邮箱和验证码。",
      fillAll: "请填写所有必填字段。"
    },
    settings: {
      title: "⚙️ 账号设置",
      subtitle: "管理您的密码、安全和账号详情。",
      reqLogin: "需要登录",
      reqLoginDesc: "请先登录以访问账号设置页面。",
      mustChangePassTitle: "需要设置新密码",
      mustChangePassDesc: "这是您第一次使用 Google 账号登录。请设置独立密码以便今后直接使用邮箱登录。",
      freeMember: "免费用户",
      vipMember: "VIP 会员",
      emailLabel: "邮箱地址",
      notSet: "未设置",
      vipExpiry: "VIP 到期时间",
      changePassTitle: "修改密码",
      currentPassLabel: "当前密码",
      currentPassPlaceholder: "输入当前密码",
      newPassLabel: "新密码",
      newPassPlaceholder: "最少 4 位字符",
      confirmPassLabel: "确认新密码",
      confirmPassPlaceholder: "再次输入新密码",
      updateBtn: "更新密码",
      updating: "正在更新...",
      passMinLen: "新密码长度至少为 4 位。",
      passMismatch: "两次输入的密码不一致。",
      passChangeSuccess: "修改密码成功！",
      passChangeError: "修改密码失败。"
    },
    developer: {
      title: "🛠️ 开发者控制台",
      subtitle: "创建和管理您的 API 密钥，以便通过 API 调用翻译和语音合成服务。",
      balance: "API 账号余额",
      vipServerRate: "VIP 权益：VIP 会员账号免费调用翻译和语音合成 API。",
      rateLimitWarning: "注意：请勿滥用 API 速率限制。",
      apiKeyListTitle: "API 密钥列表",
      createBtn: "创建新密钥",
      keyNameLabel: "密钥名称",
      keyNamePlaceholder: "输入易记名称 (例如 Chrome 插件, 翻译 App...)",
      keyNameRequired: "请输入 API 密钥名称。",
      creating: "正在创建...",
      copied: "已复制！",
      copyBtn: "复制",
      revokedStatus: "已撤销",
      activeStatus: "使用中",
      createdLabel: "创建时间",
      lastUsedLabel: "最后使用",
      neverUsed: "未使用",
      revokeBtn: "撤销密钥",
      revokeConfirm: "您确定要撤销此 API 密钥吗？所有使用此密钥的应用程序将被断开连接。",
      revokeSuccess: "API 密钥撤销成功！",
      revokeError: "撤销 API 密钥出错。",
      createSuccess: "API 密钥创建成功！请立即复制，它将不再显示：",
      createError: "创建 API 密钥出错。",
      apiDocsTitle: "API 集成文档",
      apiDocsDesc: "您可以在您的插件或应用中使用以下接口。请求时需在 Header 中传递 `X-VIP-Key: <your_api_key>` 或 `Authorization: Bearer <your_api_key>`。",
      transEndpoint: "1. 翻译 API (越文词库 / 快速翻译)",
      transPayloadDesc: "请求格式 (POST):",
      ttsEndpoint: "2. 语音合成 (TTS) API",
      ttsPayloadDesc: "请求格式 (POST):",
      voicesList: "支持的音色列表 (包括 the_gioi_hoan_my, pha_bong_cau, ...)",
      apiUsageHistoryTitle: "API 历史调用记录",
      colKey: "API 密钥",
      colModel: "模型 / 接口",
      colChars: "字符数 / 字数",
      colCost: "费用",
      colStatus: "状态",
      colTime: "调用时间",
      freeCost: "免费 (VIP)",
      emptyUsage: "暂无 API 调用记录。"
    },
    reader: {
      nextChapter: "下一章 ❯",
      prevChapter: "❮ 上一章",
      toc: "目录",
      settings: "阅读设置",
      ttsPlayer: "语音朗读播放器",
      playBtn: "播放",
      pauseBtn: "暂停",
      stopBtn: "停止",
      speed: "语速",
      voice: "音色",
      modeFast: "快速翻译版",
      modeAdvanced: "优质 VIP 翻译版",
      modeHanviet: "汉越音译版",
      loadingChapter: "⏳ 正在加载章节内容...",
      errorLoadingChapter: "❌ 加载章节失败。",
      ttsLoading: "⏳ 正在合成语音...",
      ttsError: "❌ 语音合成失败，请稍后重试。",
      epubSuccess: "成功下载 EPUB 电子书！"
    }
  }
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('preferredLanguage') || 'vi');

  useEffect(() => {
    localStorage.setItem('preferredLanguage', lang);
  }, [lang]);

  const t = translations[lang] || translations.vi;

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
export { LangContext };
